import "./globals.css";
import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";
import { getCurrentUser, getCurrentProfile } from "@/lib/auth";
import { getNotificationCounts } from "@/lib/notifications";
import type { NotificationCounts } from "@/lib/notifications-types";
import { AppShell } from "@/components/AppShell";
import { ToastProvider } from "@/components/Toast";
import { MotionGate } from "@/components/MotionGate";
import { ServiceWorkerRegister } from "@/components/pwa/ServiceWorkerRegister";
import { InstallPrompt } from "@/components/pwa/InstallPrompt";
import { IOSInstallInstructions } from "@/components/pwa/IOSInstallInstructions";

const inter = Inter({ subsets: ["latin"], display: "swap" });

export const metadata: Metadata = {
  title: "DomiRank · Ranking oficial de dominó",
  description: "DomiRank — la plataforma de ranking para jugadores de dominó. Singles, parejas y torneos.",
  manifest: "/manifest.webmanifest",
  appleWebApp: {
    capable: true,
    statusBarStyle: "black-translucent",
    title: "DomiRank",
  },
  icons: {
    apple: "/icons/apple-touch-icon-180.png",
  },
  other: {
    "mobile-web-app-capable": "yes",
  },
};

export const viewport: Viewport = {
  themeColor: "#10b981",
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  // Defensa: que un fallo en CUALQUIERA de estas queries no rompa el layout
  // entero (sino, el usuario ve global-error en cualquier ruta).
  let user: { id: string } | null = null;
  let profile: any = null;
  let counts: NotificationCounts | null = null;

  try {
    const u = await getCurrentUser();
    if (u) {
      user = { id: u.id };
      try { profile = await getCurrentProfile(); } catch (e) { console.error("[layout] profile failed:", e); }
      try { counts = await getNotificationCounts(u.id); } catch (e) { console.error("[layout] counts failed:", e); }
    }
  } catch (e) {
    console.error("[layout] getCurrentUser failed:", e);
  }

  return (
    <html lang="es" className={inter.className}>
      <head>
        {/* iOS splash screens — generated by pwa-asset-generator */}
        <link rel="apple-touch-startup-image" media="screen and (device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)" href="/icons/apple-splash-640-1136.png" />
        <link rel="apple-touch-startup-image" media="screen and (device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)" href="/icons/apple-splash-750-1334.png" />
        <link rel="apple-touch-startup-image" media="screen and (device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)" href="/icons/apple-splash-828-1792.png" />
        <link rel="apple-touch-startup-image" media="screen and (device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)" href="/icons/apple-splash-1125-2436.png" />
        <link rel="apple-touch-startup-image" media="screen and (device-width: 390px) and (device-height: 844px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)" href="/icons/apple-splash-1170-2532.png" />
        <link rel="apple-touch-startup-image" media="screen and (device-width: 393px) and (device-height: 852px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)" href="/icons/apple-splash-1179-2556.png" />
        <link rel="apple-touch-startup-image" media="screen and (device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)" href="/icons/apple-splash-1242-2688.png" />
        <link rel="apple-touch-startup-image" media="screen and (device-width: 428px) and (device-height: 926px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)" href="/icons/apple-splash-1284-2778.png" />
        <link rel="apple-touch-startup-image" media="screen and (device-width: 430px) and (device-height: 932px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)" href="/icons/apple-splash-1290-2796.png" />
        <link rel="apple-touch-startup-image" media="screen and (device-width: 768px) and (device-height: 1024px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)" href="/icons/apple-splash-1536-2048.png" />
        <link rel="apple-touch-startup-image" media="screen and (device-width: 834px) and (device-height: 1194px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)" href="/icons/apple-splash-1668-2388.png" />
        <link rel="apple-touch-startup-image" media="screen and (device-width: 1024px) and (device-height: 1366px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)" href="/icons/apple-splash-2048-2732.png" />
      </head>
      <body>
        <MotionGate>
          <ToastProvider>
            <AppShell user={user} profile={profile} counts={counts}>
              {children}
            </AppShell>
          </ToastProvider>
        </MotionGate>
        <ServiceWorkerRegister />
        <InstallPrompt />
        <IOSInstallInstructions />
      </body>
    </html>
  );
}
